### ISSUE TITLE
Firefox / Chromium discrepency

### ISSUE THREAD

**Issue by jamesb93** [lewardo/seven#1]
Firefox and Chromium treat your header CSS differently.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/13281862/132260728-6ce71f56-10ee-4ba8-a0f5-2f223ff68593.png">

To fix it you can provide a more explicit set of on your `.moreinfo` class.

It's also a good habit to define the `flex-direction` (to enforce the layout) and when necessary your `flex-basis`. https://www.youtube.com/watch?v=vQAvjof1oe4 Good video :) I assume you wanted tabs across the top as per your description so the fix would be to supply the class with the following stuffs:

```css
.moreinfo {
    display: flex;  
    flex-direction: row;
    align-items: center;
    justify-content: space-around;
    flex-wrap: wrap;
}
```

Also no need to define `width: 100%` on your `*` selector as a result.

This gives you centering too and allows the items to wrap to fit the screen. Try out different values for `justify-content`.

Next thing to fix is making your header responsive. What happens when we go to a tiny screen?

<img width="447" alt="image" src="https://user-images.githubusercontent.com/13281862/132260970-e155d64d-46c6-405e-9931-58380bba4e87.png">

Cool weekend project though! Your design skills beat mine by a country mile 🎉
